USE [master]
GO

/****** Object:  Database [S4E]    Script Date: 14/12/2023 23:08:30 ******/
CREATE DATABASE [S4E]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'S4E', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\S4E.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'S4E_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\S4E_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [S4E].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [S4E] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [S4E] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [S4E] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [S4E] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [S4E] SET ARITHABORT OFF 
GO

ALTER DATABASE [S4E] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [S4E] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [S4E] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [S4E] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [S4E] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [S4E] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [S4E] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [S4E] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [S4E] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [S4E] SET  DISABLE_BROKER 
GO

ALTER DATABASE [S4E] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [S4E] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [S4E] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [S4E] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [S4E] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [S4E] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [S4E] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [S4E] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [S4E] SET  MULTI_USER 
GO

ALTER DATABASE [S4E] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [S4E] SET DB_CHAINING OFF 
GO

ALTER DATABASE [S4E] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [S4E] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [S4E] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [S4E] SET QUERY_STORE = OFF
GO

ALTER DATABASE [S4E] SET  READ_WRITE 
GO


